# Generated by Django 5.0.1 on 2024-03-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0006_user_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaarbackpic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaarfrontpic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pancardpic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='shoppic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='sign',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
