# Generated by Django 5.0.1 on 2024-03-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0007_user_aadhaarbackpic_user_aadhaarfrontpic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ISACTIVE', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('bank_acc_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_acc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bene_id', models.IntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customerifsc', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('msrno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
