# Generated by Django 4.2.11 on 2024-04-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itpub_models", "0011_package_user_city_user_distributor_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
