# Generated by Django 5.0.1 on 2024-04-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0013_user_asm_name_user_is_asm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_id',
            new_name='bank_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
