# Generated by Django 5.0.1 on 2024-04-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0014_rename_bank_id_bank_bank_code_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
