# Generated by Django 5.0.1 on 2024-04-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0015_alter_bank_bank_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybank',
            old_name='acc_holdername',
            new_name='account_holdername',
        ),
        migrations.AddField(
            model_name='companybank',
            name='branchname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companybank',
            name='cash_deposit_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
