# Generated by Django 4.2.11 on 2024-04-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itpub_models", "0019_rename_adddate_state_created_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BBPSModelFields",
        ),
    ]
