# Generated by Django 4.2.11 on 2024-04-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itpub_models", "0022_alter_bbpsproviders_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bbpsproviders",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "ELECTRICITY"),
                    (1, "GAS"),
                    (2, "WATER"),
                    (3, "LIC"),
                    (4, "INSURANCE"),
                    (5, "MUNICIPAL TAXES AND SERVICES"),
                    (6, "FASTAG"),
                    (7, "LOAN REPAYMENT"),
                    (8, "EDUCATION FEES"),
                    (9, "BROADBAND"),
                    (10, "CABLE"),
                    (11, "TRAFFIC CHALLAN"),
                    (12, "DIGITAL VOUCHER"),
                    (13, "MOBILE"),
                    (14, "DTH"),
                    (15, "DATACARD"),
                    (16, "POSTPAID"),
                    (17, "TELEPHONE"),
                    (18, "STV"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
    ]
