# Generated by Django 4.2.11 on 2024-04-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itpub_models", "0024_alter_bbpsproviders_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
