# Generated by Django 5.0.1 on 2024-04-15 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0026_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_acc_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bene_id', models.IntegerField(blank=True, null=True)),
                ('transaction_status', models.SmallIntegerField(choices=[(3, 'PENDING'), (2, 'FAILURE'), (1, 'SUCCESS')], db_index=True)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.SmallIntegerField(choices=[(3, 'WALLET')], db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
