# Generated by Django 5.0.1 on 2024-04-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0027_wallettransactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='customer_firstname',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
