# Generated by Django 5.0.1 on 2024-04-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0028_rename_customer_name_customer_customer_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundrequest',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='username',
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='add_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
