# Generated by Django 5.0.4 on 2024-04-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "itpub_models",
            "0028_rename_customer_name_customer_customer_firstname_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="fundrequest",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="fundrequest",
            name="username",
        ),
    ]
