<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-04-18 09:57

from django.db import migrations, models
=======
# Generated by Django 5.0.4 on 2024-04-20 13:44

from django.db import migrations
>>>>>>> 9f8018004d7e7b62ab00d0219a25103f0e6659be


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('itpub_models', '0028_rename_customer_name_customer_customer_firstname_and_more'),
=======
        (
            "itpub_models",
            "0028_rename_customer_name_customer_customer_firstname_and_more",
        ),
>>>>>>> 9f8018004d7e7b62ab00d0219a25103f0e6659be
    ]

    operations = [
        migrations.RenameField(
<<<<<<< HEAD
            model_name='fundrequest',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='username',
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='add_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='update_date',
            field=models.DateField(blank=True, null=True),
=======
            model_name="fundrequest",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="fundrequest",
            name="username",
>>>>>>> 9f8018004d7e7b62ab00d0219a25103f0e6659be
        ),
    ]
