# Generated by Django 5.0.1 on 2024-04-29 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0030_usertransactions_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zpaybeneficiary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_acc_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_ifsc', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
