# Generated by Django 5.0.4 on 2024-04-29 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itpub_models", "0032_alter_userwallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwallet",
            name="user",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
