# Generated by Django 5.0.1 on 2024-05-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0035_alter_userwallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mpin',
        ),
        migrations.AlterField(
            model_name='user',
            name='tpin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
