# Generated by Django 5.0.1 on 2024-05-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0036_remove_user_mpin_alter_user_tpin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='actived_for_rnfi',
        ),
        migrations.RemoveField(
            model_name='user',
            name='app_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily_authentication',
        ),
        migrations.RemoveField(
            model_name='user',
            name='device_register',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_live_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_show_notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='user',
            name='video_kyc',
        ),
        migrations.AddField(
            model_name='user',
            name='dicashbackper',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
