# Generated by Django 5.0.1 on 2024-05-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0037_remove_user_actived_for_rnfi_remove_user_app_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parent_str',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time',
        ),
    ]
