# Generated by Django 5.0.1 on 2024-05-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0038_remove_user_parent_str_remove_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmttransactions',
            name='payment_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
