# Generated by Django 5.0.1 on 2024-05-10 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0039_dmttransactions_payment_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequest',
            name='adddate',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='approvedate',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='bank_reference',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='cashslip',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='isapproved',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='isdelete',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='isupdate',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='lastupdate',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='add_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='bank_acc_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='bank_ref_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
