# Generated by Django 5.0.1 on 2024-05-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0040_remove_fundrequest_adddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequest',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='bank_acc_number',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='bank_ref_number',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='fundrequest',
            name='update_date',
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='adddate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='approvedate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='cashslip',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='isapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='isupdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='lastupdate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
