# Generated by Django 5.0.6 on 2024-05-22 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0042_paysprintbanks_alter_bankdetails_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='registered_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itpub_models.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='available_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
