# Generated by Django 5.0.6 on 2024-05-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0043_alter_bankdetails_registered_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmttransactions',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
