# Generated by Django 5.0.6 on 2024-05-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0044_alter_dmttransactions_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dicashbackper',
            new_name='compback',
        ),
        migrations.AddField(
            model_name='user',
            name='diback',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='retback',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dmttransactions',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
