# Generated by Django 5.0.6 on 2024-05-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0045_rename_dicashbackper_user_compback_user_diback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZpayBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vpa', 'VPA'), ('account_number', 'Account Number')], default='account_number', max_length=20)),
                ('bene_id', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itpub_models.customer')),
            ],
        ),
    ]
