# Generated by Django 5.0.6 on 2024-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0046_zpaybankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='zpaybankdetail',
            name='upi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
