# Generated by Django 5.0.6 on 2024-05-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0047_zpaybankdetail_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='available_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
