# Generated by Django 5.0.6 on 2024-05-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0048_alter_userwallet_available_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='available_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
