# Generated by Django 5.0.6 on 2024-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0049_alter_userwallet_available_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmttransactions',
            name='bene_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
