# Generated by Django 5.0.6 on 2024-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0051_alter_dmttransactions_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransactions',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='usertransactions',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='usertransactions',
            name='update_date',
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='adddate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='approvedate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='cashslip',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='lastupdate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='transaction_status',
            field=models.SmallIntegerField(choices=[(3, 'PENDING'), (2, 'FAILURE'), (1, 'SUCCESS'), (4, 'REINITIATE')], db_index=True),
        ),
    ]
