# Generated by Django 5.0.6 on 2024-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0052_remove_usertransactions_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='adddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='approvedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='lastupdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
