# Generated by Django 5.0.6 on 2024-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0054_usertransactions_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='approvedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='lastupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='payment_mode',
            field=models.SmallIntegerField(choices=[(8, 'IMPS_RTGS_NEFT'), (4, 'CASH'), (5, 'UPI'), (9, 'CHEQUE_DD')], db_index=True),
        ),
    ]
