# Generated by Django 5.0.6 on 2024-06-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0057_alter_usertransactions_add_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTransactions',
            new_name='FundRequests',
        ),
    ]
