# Generated by Django 5.0.6 on 2024-06-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0059_remove_wallettransactions_bank_acc_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='closing_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='opening_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(2, 'WALLET'), (1, 'DMT'), (3, 'BBPS'), (4, 'UPI')], db_index=True),
        ),
    ]
