# Generated by Django 5.0.6 on 2024-06-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0060_wallettransactions_closing_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequests',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
