# Generated by Django 5.0.6 on 2024-06-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0061_fundrequests_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='transaction_direction',
            field=models.SmallIntegerField(choices=[(1, 'DEBIT'), (2, 'CREDIT')], db_index=True, default=2),
            preserve_default=False,
        ),
    ]
