# Generated by Django 5.0.6 on 2024-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0062_wallettransactions_transaction_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='transaction_direction',
            field=models.SmallIntegerField(choices=[(1, 'DEBIT'), (2, 'CREDIT')], db_index=True, null=True),
        ),
    ]
