# Generated by Django 5.0.6 on 2024-06-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0063_alter_wallettransactions_transaction_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransactions',
            old_name='created_at',
            new_name='created',
        ),
    ]
