# Generated by Django 5.0.6 on 2024-06-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0064_rename_created_at_wallettransactions_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransactions',
            name='created',
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='trans_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
