# Generated by Django 5.0.6 on 2024-06-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0065_remove_wallettransactions_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='trans_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
