# Generated by Django 5.0.6 on 2024-06-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0066_alter_wallettransactions_trans_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransactions',
            name='trans_date',
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
