# Generated by Django 5.0.6 on 2024-06-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0067_remove_wallettransactions_trans_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='amount',
            field=models.FloatField(),
        ),
    ]
