# Generated by Django 5.0.6 on 2024-06-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0070_wallettowallet_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WallettoWallet_transaction',
            new_name='Wallet_to_Wallet_transaction',
        ),
    ]
