# Generated by Django 5.0.6 on 2024-06-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0071_rename_wallettowallet_transaction_wallet_to_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_to_wallet_transaction',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet_to_wallet_transaction',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
