# Generated by Django 5.0.6 on 2024-06-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0072_wallet_to_wallet_transaction_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequests',
            name='opening_balance',
        ),
        migrations.AddField(
            model_name='fundrequests',
            name='start_closing_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundrequests',
            name='start_opening_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundrequests',
            name='upd_closing_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundrequests',
            name='upd_opening_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet_to_wallet_transaction',
            name='receivername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dmttransactions',
            name='bene_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dmttransactions',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequests',
            name='running_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
