# Generated by Django 5.0.6 on 2024-06-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0073_remove_fundrequests_opening_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequests',
            name='payment_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
