# Generated by Django 5.0.6 on 2024-06-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0074_fundrequests_payment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmttransactions',
            name='comission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmttransactions',
            name='tds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dmttransactions',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dmttransactions',
            name='charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
