# Generated by Django 5.0.6 on 2024-06-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0075_dmttransactions_comission_dmttransactions_tds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_to_wallet_transaction',
            name='charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet_to_wallet_transaction',
            name='comission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet_to_wallet_transaction',
            name='tds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet_to_wallet_transaction',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
