# Generated by Django 5.0.6 on 2024-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0076_wallet_to_wallet_transaction_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_to_wallet_transaction',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
