# Generated by Django 5.0.6 on 2024-06-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0077_wallet_to_wallet_transaction_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet_to_wallet_transaction',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='wallet_to_wallet_transaction',
            name='comission',
        ),
        migrations.RemoveField(
            model_name='wallet_to_wallet_transaction',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='wallet_to_wallet_transaction',
            name='tds',
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='comission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='tds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
