# Generated by Django 5.0.6 on 2024-06-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0078_remove_wallet_to_wallet_transaction_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbpsproviders',
            name='comission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bbpsproviders',
            name='compback',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bbpsproviders',
            name='diback',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bbpsproviders',
            name='retback',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='available_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
