# Generated by Django 5.0.6 on 2024-06-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0080_remove_bbpsproviders_comission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='ISACTIVE',
        ),
        migrations.RemoveField(
            model_name='package',
            name='company_back',
        ),
        migrations.RemoveField(
            model_name='package',
            name='distributor_back',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_distributor',
        ),
        migrations.RemoveField(
            model_name='package',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='package',
            name='surcharge',
        ),
        migrations.RemoveField(
            model_name='package',
            name='tds',
        ),
        migrations.AddField(
            model_name='bbpstransactions',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='end_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_flat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='pack_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='pack_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='start_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
