# Generated by Django 5.0.6 on 2024-06-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0081_remove_package_isactive_remove_package_company_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbpstransactions',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
