# Generated by Django 5.0.6 on 2024-06-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0082_bbpstransactions_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bc_registration_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='end_val',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hold_amt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_pin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='on_hold',
        ),
        migrations.RemoveField(
            model_name='user',
            name='psa_id_pan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='start_val',
        ),
    ]
