# Generated by Django 5.0.6 on 2024-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0083_remove_user_bc_registration_id_remove_user_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbpstransactions',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
