# Generated by Django 5.0.6 on 2024-06-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0086_surcharge_delete_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surcharge',
            old_name='s100001to500000',
            new_name='flat_s101to2000',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='s10001to50000',
            new_name='perc_s100001to500000',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='s101to2000',
            new_name='perc_s10001to50000',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='s2001to5000',
            new_name='perc_s2001to5000',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='s500001toall',
            new_name='perc_s500001toall',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='s50001to100000',
            new_name='perc_s50001to100000',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='s5001to10000',
            new_name='perc_s5001to10000',
        ),
    ]
