# Generated by Django 5.0.6 on 2024-06-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0087_rename_s100001to500000_surcharge_flat_s101to2000_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbpstransactions',
            old_name='created_at',
            new_name='add_date',
        ),
        migrations.RemoveField(
            model_name='fundrequests',
            name='created_at',
        ),
    ]
