# Generated by Django 5.0.6 on 2024-06-11 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0088_rename_created_at_bbpstransactions_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequests',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 11, 10, 57, 41, 309909, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
