# Generated by Django 5.0.6 on 2024-06-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpub_models', '0089_alter_fundrequests_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbpstransactions',
            old_name='add_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='flat_s101to2000',
            new_name='bbps_allperc',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='perc_s100001to500000',
            new_name='dmtflat_s101to2000',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='perc_s10001to50000',
            new_name='dmtperc_s100001to500000',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='perc_s2001to5000',
            new_name='dmtperc_s10001to50000',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='perc_s500001toall',
            new_name='dmtperc_s2001to5000',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='perc_s50001to100000',
            new_name='dmtperc_s500001toall',
        ),
        migrations.RenameField(
            model_name='surcharge',
            old_name='perc_s5001to10000',
            new_name='dmtperc_s50001to100000',
        ),
        migrations.AddField(
            model_name='bbpstransactions',
            name='charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='dmtperc_s5001to10000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='payoutflat_s101to2000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='payoutperc_s100001to500000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='payoutperc_s10001to50000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='payoutperc_s2001to5000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='payoutperc_s500001toall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='payoutperc_s50001to100000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='payoutperc_s5001to10000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='upiflat_s101to2000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='upiperc_s100001to500000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='upiperc_s10001to50000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='upiperc_s2001to5000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='upiperc_s500001toall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='upiperc_s50001to100000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='upiperc_s5001to10000',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
